### ISSUE TITLE
Looking to reproduce inference results on 3090

### ISSUE THREAD

**Issue by rbavery** [BloodAxe/xView3-The-First-Place-Solution#3]
Hello! I realize this is an old repo so no worries if this is unmaintained. But was curious if you had any suggestions on dealing with OOM errors when running inference on a single 3090 GPU with 24Gb memory. I'm able to trace the model but inference fails after a minute or two on the first scene when running `python submit_multilabel_ensemble.py configs/inference/1128_b5_b4_vs2_fliplr.yaml`. 

Things I've tried to reduce memory:
* reduce both the tile step and tile stride by a factor of 2 and 4, but I still get OOM errors.

```
Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!

7it [00:43,  3.84s/it][1]    7586 killed     python submit_multilabel_ensemble.py 
```
* turn off tta

**Comment by rbavery** [comment]
It looks like the traced model I produced was not equivalent to the traced model downloaded from this repo's release. But when using the traced model downloaded from the repo, inference still fails after a longer period of time (10 minutes) on my Nvidia 3090.

**Comment by rbavery** [comment]
It seems like there's some difference between the single process inference in the conda environment vs the docker image inference. inference completes when running with the docker image

```
→ docker run --gpus all --rm -it -v /mnt/second2tb/xview/test:/mnt/second2tb/xview/test ekhvedchenyateam/xview3:72 $XVIEW3_DIR/test 02649c5fc4f85dadp ./result_02649c5fc4f85dadp.csv

{'ensemble': 'submissions/1128_b5_b4_vs2_fliplr/traced_ensemble.jit', 'inference': {'channels_last': False, 'use_traced_model': True, 'tile_size': 2048, 'tile_step': 1536, 'accumulate_on_gpu': False, 'batch_size': 1, 'fp16': True}, 'thresholds': {'objectness_threshold': 0.3, 'vessel_threshold': 0.338, 'fishing_threshold': 0.35}}
Loaded ensemble from submissions/1128_b5_b4_vs2_fliplr/traced_ensemble.jit
223it [12:01,  3.23s/it]
Saved predictions to ./result_02649c5fc4f85dadp.csv

```

memory use stays very low during docker inference, about 7-8Gb.

**Comment by BloodAxe** [comment]
I also used 3090 for training and testing this solution, so "It worked for me" situation 🤷‍♂️ 
The fact that docker inference works indicates maybe something is different on your local environment.

So maybe you want to check what is different between container and your environment. 

The "7586 killed" does not tell much tbh. Do you have CUDA OOM or regular RAM OOM? Try doing CPU-only inference to rule this out (You may need to change some pieces of code that moves data to GPU).

Add print statements to trace the execution progress and try running inference a few times. Maybe you will be able to spot a repeating pattern of crashes.

**Comment by rbavery** [comment]
Got it thank you for the tips
